# Generated by Django 3.0.6 on 2020-05-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200525_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
